### ISSUE TITLE
Fraction in day_of_year and UTC_hour redundant?

### ISSUE THREAD

**Issue by iljah** [juppiega/IL2017#1]
Fortran test program specifies both:
```
day_of_year = 105.66
UTC_hour = 16
```
where 0.66/1 is (almost) the same as 16/24. The result will be different if I change only one of them compared to changing both, which seems inconsistent. Since fraction of day of year can be derived from utc hour I suggest changing DoY input to integer and switching to floating point internally based on given hour.

**Comment by juppiega** [comment]
Thanks for the feedback! The issue has been fixed in f7aa642

The model now casts day_of_year internally to a double-precision floating point, including a fraction using the UTC_hour input. This is then used to compute the annual parameterization and Sun's position. UTC_hour is used in the diurnal parameterization, which was not affected by the fraction in doy -- hence causing an inconsistency.

**Comment by juppiega** [comment]
Oh, and this also changed the last decimals of the test case. I've now updated the values in README and IL2017_test.f90.
